# Generated by Django 5.0.6 on 2024-06-28 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_book'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='post',
        ),
    ]
